services:
  casaos-backup-manager:
    container_name: casaos-backup-manager
    build:
      context: .
    image: casaos-backup-manager:latest

    ports:
      - "8088:8000"

    environment:
      TZ: Europe/Madrid
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: /app
      HOST_PROC: /host/proc
      HOST_SYS: /host/sys
      # Configura la ruta de guardado en el disco externo
      BACKUP_TARGET_DIR: /media/pichules/08684ab9-10b8-46bc-a6f2-a19f3adfc6fa/Backups/CasaOS

    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host_root:ro
      - /DATA:/DATA:ro
      - /media/pichules:/media/pichules:rw  # <-- Da acceso de escritura al disco externo
      - /var/lib/casaos:/var/lib/casaos:ro
      - /mnt:/mnt:ro
      - ./data:/data

    restart: unless-stopped